#!/bin/bash

function printHelp(){
    echo This is a calculator with variable saving
    echo to launch in terminal run calcer -s
    echo without -s calcer will start in a new terminal

}

if [[ $1 == "-s" ]];
then
    echo Ctr+C to exit
    exec java -jar /usr/bin/JCalc.jar 
elif [[ $1 == "-h"  ]];
then
    printHelp
else
    exec kitty java -jar /usr/bin/JCalc.jar &
fi

